### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by razzeee** [billstclair/elm-sortable-table#2]
Not sure, not an native speaker. But `resorts` in this line https://github.com/billstclair/elm-sortable-table/blob/1.1.0/src/Table.elm#L141 should probably be `records`?

**Comment by billstclair** [comment]
Should probably be spelled "re-sorts", as in sorts again, since "resorts" is easy to read as multiple fancy ocean-front hotels.

**Comment by razzeee** [comment]
That makes even more sense :)
