### ISSUE TITLE
Allow reversed initial sort

### ISSUE THREAD

**Issue by LemonIceScream** [billstclair/elm-sortable-table#3]
I have a table with a date column that I wish to display initially in descending order. This is not possible because the initialSort function only allows initial data to be sorted in ascending order.

Relevant issue from original library: https://github.com/evancz/elm-sortable-table/issues/9

I believe extending the initialSort function to accept either a Bool, Sorter or a new Order type would be ideal.

Thanks for maintaining this nifty little library!

**Comment by coryc5** [comment]
@gaul had a PR that implemented this functionality, which could be a good starting point:
https://github.com/evancz/elm-sortable-table/pull/30

**Comment by MarkFarmiloe** [comment]
There is already a way to initially sort the data by any column either ascending or descending - simply use Table.initialSort to choose the column and set that column's sorter to either Table.decreasingBy or Table.decreasingOrIncreasingBy. The problem imho is with the sort-state arrows in the header. If there is only one sort available, whether that is ascending or descending, it is shown as a down arrow. Similarly if the column can be sorted either way, then the first sort is displayed as a down arrow whether this is descending or ascending. The function that needs changing is toHeaderInfo. I'll shortly do a pull request which you can accept if you agree with me :-)

**Comment by billstclair** [comment]
Fixed in version 1.1.3 by 959a821 and 01d1e0f.

Thank you to @MarkFarmiloe for doing this.
