### ISSUE TITLE
sorting two columns produces vdom errors

### ISSUE THREAD

**Issue by purei** [billstclair/elm-sortable-table#4]
Chrome, Firefox and Safari all show a barrage of this error:
`Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`

at 
https://billstclair.github.io/elm-sortable-table/travel.html

reproduce by clicking Price to sort, then click Rating to sort

**Comment by billstclair** [comment]
I can reproduce this. Will look at it soon.

**Comment by MarkFarmiloe** [comment]
I looked at this and got very concerned as it appeared to be a problem with Elm itself. So I asked on Slack and ilias worked out the problem so quickly! The elm.json is (indirectly) referencing an out-of-date version of elm/virtual-dom. Bump the version to 1.0.2 and all works as it should.

**Comment by billstclair** [comment]
Oops. I didn't notice @MarkFarmiloe's pull request before I fixed this in 2d66365.

Will look at that pull request now.
